
[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-steputils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  name = "github.com/mholt/archiver"
  version = "3.1.1"

[prune]
  go-tests = true
  unused-packages = true
